db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/postgres?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
db.username=postgres
db.password=bonda10bonda10

hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

